name: Sample Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-samples:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-2022

    steps:
    - name: Update VS2022 preview
      shell: bash
      run: |
        dotnet tool update -g dotnet-vs
        vs modify preview +mobile +xamarin +core +desktop +uwp +web
        echo "##vso[task.prependpath]$(vs where preview --prop=InstallationPath)\MSBuild\Current\Bin"

    - name: Install Windows SDK 10.0.16299
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://go.microsoft.com/fwlink/p/?linkid=864422 -OutFile winsdk.exe
        $startInfo = New-Object System.Diagnostics.ProcessStartInfo
        $startInfo.FileName = "winsdk.exe"
        $startInfo.Arguments = "/norestart /quiet"
        $process = New-Object System.Diagnostics.Process
        $process.StartInfo = $startInfo
        $process.Start()
        $process.WaitForExit()

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        lfs: true

    # Install the .NET Core workload
    - name: Install .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Install .NET 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install .NET 6
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Install DotNet workloads
      shell: bash
      run: |
        dotnet workload install android
        dotnet workload install ios
        dotnet workload install tvos
        dotnet workload install macos
        dotnet workload install maui
        dotnet tool install -g Redth.Net.Maui.Check
        maui-check --non-interactive --fix

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore/Build the sample
      run: msbuild SextantSample.sln /t:restore,build /maxcpucount /p:NoPackageAnalysis=true /verbosity:minimal /p:Configuration=$env:Configuration
      working-directory: Sample
      env:
        Configuration: ${{ matrix.configuration }}
